language: go
go:
  - 1.7

sudo: false

branches:
  only:
    - master

before_install:
  - wget http://apache.claz.org/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz
  - tar -zxf zookeeper*tar.gz
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./zk

after_success:
  - bash <(curl -s https://codecov.io/bash)
 
